spring.application.name=wallet

spring.datasource.url=jdbc:mysql://localhost:3306/hcl_wallet
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

#server.error.whitelabel.enabled=true
#spring.mvc.throw-exception-if-no-handler-found=false
#server.error.include-message=always